name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: 'Get .env file from Github'
      run: echo "${{secrets.ENV_PRODUCTION}}" > .env.production
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag khoinguyen0211/pops:v1
    - name: 'Log in to DockerHub'
      run: docker login -u ${{secrets.DOCKER_HUB_USERNAME}} -p ${{secrets.DOCKER_HUB_PASSWORD}}
    - name: 'Push my image to DockerHub' 
      run: docker push khoinguyen0211/pops:v1